### ISSUE TITLE
Inconsistency between the code and the doc of WithFees.getFeeRecipients and WithFees.getFeeBps

### ISSUE THREAD

**Issue by DocCon-team** [1001-digital/erc721-extensions#12]
Hi,

The doc of the functions `WithFees.getFeeRecipients` and `WithFees.getFeeBps` refers to a contract named "`HasSecondarySalesFees`", which is different from the actual contract name `HasSecondarySaleFees` in the code base.

https://github.com/1001-digital/erc721-extensions/blob/2eb920b0e5091324581b636b7b1f6c9097b1e2d9/contracts/WithFees.sol#L28

https://github.com/1001-digital/erc721-extensions/blob/2eb920b0e5091324581b636b7b1f6c9097b1e2d9/contracts/WithFees.sol#L37

Could you please check it?

Thanks.

**Comment by jwahdatehagh** [comment]
Thanks for this catch!
