### ISSUE TITLE
Suggesting updates on WithMarketOffers._cancelOffer and WithMarketOffers._makeOffer

### ISSUE THREAD

**Issue by DocCon-team** [1001-digital/erc721-extensions#13]
Hi,

The function `WithMarketOffers._cancelOffer` emits an `OfferWithdrawn` event, which is not documented in its doc.

https://github.com/1001-digital/erc721-extensions/blob/2eb920b0e5091324581b636b7b1f6c9097b1e2d9/contracts/WithMarketOffers.sol#L100

A potential fix could be adding "Emits an `OfferWithdrawn` event" to the doc of this function (Line 97).

Furthermore, as functions `WithMarketOffers._beforeTokenTransfer` and `WithMarketOffers.cancelOffer` both call the function `_cancelOffer`, they emit the `OfferWithdrawn` event as well. Potential fixes could be adding "Emits an `OfferWithdrawn` event" to the doc of these functions.

Similarly, function `WithMarketOffers._makeOffer` emits a `OfferCreated` event, which is not documented in its doc.

https://github.com/1001-digital/erc721-extensions/blob/2eb920b0e5091324581b636b7b1f6c9097b1e2d9/contracts/WithMarketOffers.sol#L94

This event is also transitively emitted by functions `WithMarketOffers.makeOffer` and `WithMarketOffers.makeOfferTo` since they both call the function `_makeOffer`.

Potential fixes could be adding "Emits an `OfferCreated` event" to the doc of these functions.

Could you please check it?

Thanks.

**Comment by jwahdatehagh** [comment]
Fixed by https://github.com/1001-digital/erc721-extensions/commit/df6bb63cc944e8f4cdfc21da4f4de0c47d3838ae
