### ISSUE TITLE
Missing file CheckAddress.sol

### ISSUE THREAD

**Issue by do-web** [1001-digital/erc721-extensions#3]
ParserError: Source "@1001-digital/check-address/contracts/CheckAddress.sol" not found
 --> @1001-digital/erc721-extensions/contracts/LimitedTokensPerWallet.sol:5:1

**Comment by jwahdatehagh** [comment]
Hey @do-web - have you installed it?

`npm install @1001-digital/check-address` / `yarn add @1001-digital/check-address`...

**Comment by jwahdatehagh** [comment]
Check its readme as well: https://github.com/1001-digital/check-address

**Comment by jwahdatehagh** [comment]
Ooh it's in the `devDependencies` but should be in the `peerDependencies` in the package json. Thank you!

- Will fix with the next update!
